# Generated by Django 4.2.5 on 2023-09-28 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("admin_module", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city_code",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Наименование"
                    ),
                ),
                (
                    "city_name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование города"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        max_length=10, verbose_name="Логин, кем создана запись"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        max_length=10, verbose_name="Логин, вносивший изменение"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        verbose_name="Сокращенное название валюты",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=255, verbose_name="Полное название валюты"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        max_length=10, verbose_name="Логин, кем создана запись"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        max_length=10, verbose_name="Логин, вносивший изменение"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
            ],
            options={
                "verbose_name": "Валюта",
                "verbose_name_plural": "Валюты",
            },
        ),
        migrations.CreateModel(
            name="GPACode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gpa_code",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Наименование"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Описание"),
                ),
                (
                    "gpa_full_name",
                    models.CharField(
                        max_length=255, verbose_name="Полное наименование"
                    ),
                ),
                (
                    "oracle_code",
                    models.CharField(max_length=255, verbose_name="Код поставщика"),
                ),
                (
                    "created_by",
                    models.CharField(
                        max_length=10, verbose_name="Логин, кем создана запись"
                    ),
                ),
                ("currency", models.CharField(max_length=255, verbose_name="Валюта")),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        max_length=10, verbose_name="Логин, вносивший изменение"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
            ],
            options={
                "verbose_name": "Код агента",
                "verbose_name_plural": "Коды агентов",
            },
        ),
        migrations.CreateModel(
            name="Subclass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_code", models.CharField(max_length=255, verbose_name="Код")),
                (
                    "name_description",
                    models.CharField(max_length=255, verbose_name="Описание"),
                ),
                (
                    "created_by",
                    models.CharField(
                        max_length=10, verbose_name="Логин, кем создана запись"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        max_length=10, verbose_name="Логин, вносивший изменение"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
            ],
            options={
                "verbose_name": "Вид почты",
                "verbose_name_plural": "Виды почты",
            },
        ),
        migrations.CreateModel(
            name="SdrRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=5, max_digits=10, verbose_name="Тариф"
                    ),
                ),
                ("date_begin", models.DateField(verbose_name="Дата начала")),
                ("date_end", models.DateField(verbose_name="Дата окончания")),
                (
                    "created_by",
                    models.CharField(
                        max_length=10, verbose_name="Логин, кем создана запись"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        max_length=10, verbose_name="Логин, вносивший изменение"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "city_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sdr_rates_city_1",
                        to="admin_module.city",
                        verbose_name="Город 1",
                    ),
                ),
                (
                    "city_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sdr_rates_city_2",
                        to="admin_module.city",
                        verbose_name="Город 2",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тариф SDR",
                "verbose_name_plural": "Тарифы SDR",
            },
        ),
        migrations.CreateModel(
            name="OIRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gpa_id", models.CharField(max_length=255, verbose_name="GPA ID")),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=5, max_digits=10, verbose_name="Тариф"
                    ),
                ),
                ("date_begin", models.DateField(verbose_name="Дата начала")),
                ("date_end", models.DateField(verbose_name="Дата окончания")),
                (
                    "created_by",
                    models.CharField(
                        max_length=10, verbose_name="Логин, кем создана запись"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        max_length=10, verbose_name="Логин, вносивший изменение"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "city_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oi_rates_city_1",
                        to="admin_module.city",
                        verbose_name="Город 1",
                    ),
                ),
                (
                    "city_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oi_rates_city_2",
                        to="admin_module.city",
                        verbose_name="Город 2",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тариф OI",
                "verbose_name_plural": "Тарифы OI",
            },
        ),
        migrations.CreateModel(
            name="KZDRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_begin", models.DateField(verbose_name="Дата начала")),
                ("date_end", models.DateField(verbose_name="Дата окончания")),
                (
                    "rate_po",
                    models.DecimalField(
                        decimal_places=5, max_digits=10, verbose_name="Тариф PO"
                    ),
                ),
                (
                    "rate_nw",
                    models.DecimalField(
                        decimal_places=5, max_digits=10, verbose_name="Тариф NW"
                    ),
                ),
                (
                    "rate_ems",
                    models.DecimalField(
                        decimal_places=5, max_digits=10, verbose_name="Тариф EMS"
                    ),
                ),
                (
                    "rate_eli",
                    models.DecimalField(
                        decimal_places=5, max_digits=10, verbose_name="Тариф ELI"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        max_length=10, verbose_name="Логин, кем создана запись"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        max_length=10, verbose_name="Логин, вносивший изменение"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "city_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kzd_rates_city_1",
                        to="admin_module.city",
                        verbose_name="Город 1",
                    ),
                ),
                (
                    "city_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kzd_rates_city_2",
                        to="admin_module.city",
                        verbose_name="Город 2",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тариф KZD",
                "verbose_name_plural": "Тарифы KZD",
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=5, max_digits=10, verbose_name="Значение"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        max_length=10, verbose_name="Логин, кем создана запись"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        max_length=10, verbose_name="Логин, вносивший изменение"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "rate_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_rate_1",
                        to="admin_module.currency",
                        verbose_name="Валюта 1",
                    ),
                ),
                (
                    "rate_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_rate_2",
                        to="admin_module.currency",
                        verbose_name="Валюта 2",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обменный курс",
                "verbose_name_plural": "Обменные курсы",
            },
        ),
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=5, max_digits=10, verbose_name="Значение"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        max_length=10, verbose_name="Логин, кем создана запись"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        max_length=10, verbose_name="Логин, вносивший изменение"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "gpa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_module.gpacode",
                        verbose_name="Связанный GPA",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комиссия",
                "verbose_name_plural": "Комиссии",
            },
        ),
    ]
