# Generated by Django 4.2.4 on 2023-10-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_module", "0002_city_currency_gpacode_subclass_sdrrate_oirate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="roles",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("Senior", "Senior"), ("User", "User")],
                max_length=255,
            ),
        ),
    ]
