# Generated by Django 4.2.4 on 2023-10-15 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("admin_module", "0003_alter_userprofile_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gpacode",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_module.currency",
                verbose_name="Валюта",
            ),
        ),
    ]
