# Generated by Django 4.2.4 on 2023-10-16 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("admin_module", "0004_alter_gpacode_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="created_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
    ]
