# Generated by Django 4.2.4 on 2023-11-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_module", "0005_alter_city_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kzdrate",
            name="rate_eli",
            field=models.DecimalField(
                decimal_places=5, max_digits=10, null=True, verbose_name="Тариф ELI"
            ),
        ),
    ]
