# Generated by Django 4.2.4 on 2023-11-16 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_module", "0006_alter_kzdrate_rate_eli"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kzdrate",
            name="rate_eli",
        ),
    ]
