# Generated by Django 4.2.6 on 2023-12-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0009_records_delete_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdrrate',
            name='rate',
            field=models.FloatField(verbose_name='Тариф'),
        ),
    ]
