# Generated by Django 4.2.7 on 2023-12-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_module", "0010_alter_sdrrate_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="records",
            name="FltDate",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="records",
            name="GroupDate",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="records",
            name="Wgt",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
